# Generated by Django 4.0.5 on 2022-06-08 18:09

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название кнопки')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Внешняя ссылка')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='muzikantoff_admin.menu', verbose_name='Выберите категорию:')),
            ],
            options={
                'verbose_name': 'меню',
                'verbose_name_plural': 'Меню бота',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.IntegerField(editable=False, unique=True, verbose_name='Телеграм ID пользователя')),
                ('first_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('last_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Дата удаления')),
                ('is_baned', models.BooleanField(default=False, verbose_name='Пользователь заблокирован')),
                ('is_blocked_bot', models.BooleanField(default=False, editable=False, verbose_name='Пользователь заблокировал бота')),
            ],
            options={
                'verbose_name': 'пользователя',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('last_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('stock_name', models.CharField(max_length=50, verbose_name='Название розыгрыша')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('stock_id', models.IntegerField(editable=False)),
                ('participant_id', models.IntegerField(editable=False)),
            ],
            options={
                'verbose_name': 'розыгрыши',
                'verbose_name_plural': 'Розыгрыши',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=50, verbose_name='Заголовок поста')),
                ('text', models.TextField(max_length=4095, verbose_name='Текст поста')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Внешняя ссылка')),
                ('is_stock', models.BooleanField(default=False, verbose_name='Это является розыгрышем?')),
                ('menu', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post', to='muzikantoff_admin.menu', verbose_name='Выберите категорию:')),
            ],
            options={
                'verbose_name': 'посты',
                'verbose_name_plural': 'Посты',
            },
        ),
    ]
