# Generated by Django 4.0.5 on 2022-06-09 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muzikantoff_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='draw_end_date',
            field=models.DateTimeField(blank=None, editable=False, null=True, verbose_name='Дата окончания розыгрыша'),
        ),
    ]
