# Generated by Django 4.0.5 on 2022-06-09 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muzikantoff_admin', '0004_alter_post_draw_end_date_alter_post_header_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='draw_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания розыгрыша'),
        ),
    ]
